env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 10
  sourceType: module
parser: babel-eslint
rules:
  no-invalid-regexp: warn
  no-unreachable: warn
  no-eval: warn
  vars-on-top: warn
  indent: 
    - warn
    - 2
    - SwitchCase: 1
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
    - omitLastInOneLineBlock: true
  no-var: error
  prefer-const: warn
  prefer-template: error
  no-prototype-builtins: 0